### PR TITLE
Mobile map fix

### LINKED ISSUE #1474: Gyms and map dragging / zooming
Incorrect behavior on mobile
## Expected Behavior

Tooltip only open on a tap, map should be draggable from any poiny
## Current Behavior

Dragging or zooming map on gyms open the tooltip on mobile
## Steps to Reproduce (for bugs)

Load a map with dense gyms markers, try to pinch or drag from a gym marker
## Your Environment

Chrome and firefox on android

### PR DESCRIPTION
**Pull request by Rook25**
## Description

Prevented the pop ups that show whenever attempting to scroll/zoom/pan the map using mobile/touch devices. This change also affects how gyms are handled when 'Use Gym Sidebar' is enabled. Now, you will only get the sidebar and the popup won't show which is preferable on mobile devices.

## Motivation and Context

When a map is densely populated it makes scrolling quite difficult since info markers get shown all the time. This should fix #1474 

## How Has This Been Tested?

Have tested using my own map setup and seems to work for the default android browser as well as chrome on android.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: static/js/map.js [hunk 1]
```diff
@@ -878,11 +880,13 @@ function addListeners (marker) {
     marker.persist = null
   })
 
-  marker.addListener('mouseover', function () {
-    marker.infoWindow.open(map, marker)
-    clearSelection()
-    updateLabelDiffTime()
-  })
+  if (!isMobileDevice() && !isTouchDevice()) {
```
Comment (onilton) [inline static/js/map.js]: `||`  instead of  `&&`?

File: static/js/map.js [hunk 2]
```diff
@@ -684,11 +684,13 @@ function setupGymMarker (item) {
       marker.persist = null
     })
 
-    marker.addListener('mouseover', function () {
-      marker.infoWindow.open(map, marker)
-      clearSelection()
-      updateLabelDiffTime()
-    })
+    if (!isMobileDevice() && !isTouchDevice()) {
```
Comment (onilton) [inline static/js/map.js]: `||`  instead of  `&&`?

**Comment by ultrafunkamsterdam** [comment]
Goed verzonnen ;)
